use_lockfile = false

[project]
name = "scicalc"
r_version = "4.5"

repositories = [
  { alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-09-29/"},
]

dependencies = [
  "devtools",
	"covr",
  {name = "scicalc", path = ".", dependencies_only = true, install_suggestions = true},
    "gt",
]
