# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  pull_request:
    branches: main

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: '4.5'}
          - {os: macos-latest,   r: '4.4'}
          - {os: macos-latest,   r: '4.3'}
          - {os: windows-latest, r: '4.5'}
          - {os: windows-latest, r: '4.4'}
          - {os: windows-latest, r: '4.3'}
          - {os: ubuntu-latest,   r: '4.5'}
          - {os: ubuntu-latest,   r: '4.4'}
          - {os: ubuntu-latest,   r: '4.3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: a2-ai/setup-rv@main
      - name: replace-rversion
        run: |
          # we need to replace r_version = "4.x" with the matrixed R version
          echo "--- Replacing r_version with: ${{ matrix.config.r }} ---"
          sed -i -E 's|^r_version = "4\.[0-9\.]+"$|r_version = "'"${{ matrix.config.r }}"'"|' rproject.toml
          cat rproject.toml
        if: runner.os != 'Windows'
      - name: replace-rversion (windows)
        run: |
          Write-Host "--- Replacing r_version with: ${{ matrix.config.r }} ---"
          # Replace r_version using PowerShell
          (Get-Content rproject.toml) -replace '^r_version = "4\.[0-9\.]+", 'r_version = "${{ matrix.config.r }}"' | Set-Content rproject.toml
          Get-Content rproject.toml
        shell: pwsh
        if: runner.os == 'Windows'
      - name: rv-plan
        run: |
          rv plan
      - name: rv-sync
        run: |
          rv sync
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
